replicaCount: 1

image:
  repository: grafana/grafana
  tag: "10.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort       # You can change this to ClusterIP, LoadBalancer, etc.
  port: 80             # Exposed service port
  targetPort: 3000     # Container port Grafana listens on
  nodePort: 31147      # Optional; omit if letting Kubernetes auto-assign

resources: {}
