name: Deploy Workflow (Feature Branch)

on:
  push:
    branches:
      - feature/auth-setup

jobs:
  dummy-job:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Print success message
        run: echo "Workflow triggered successfully from feature/auth-setup branch."

